#[theme]
#name = "solarized-dark"
#[theme.overrides]
#idle_bg = "#81a1c1"
#idle_fg = "#4c566a"
#info_bg = "#7995a1"
#info_fg = "#4c566a"
#good_bg = "#a3be8c"
#good_fg = "#4c566a"
#warning_bg = "#ebcb8b"
#warning_fg = "#4c566a"
#critical_bg = "#bf616a"
#critical_fg = "#4c566a"
[theme]
name = "nord-dark"

[[block]]
block = "sound"

[[block]]
block = "cpu"

[[block]]
block = "memory"
format_mem = "MEM {mem_used_percents:1}"
icons = false
clickable = false

[[block]]
block = "load"
info = 1
warning = 2
critical = 4

[[block]]
block = "disk_space"
format = "/ {available}"

[[block]]
block = "time"
interval = 60
format = "%b %d, %R"
